cluster.name: "docker-cluster"
network.host: 0.0.0.0
#index.number_of_replicas: 0 # does not work for 5.x
#path.logs: /var/log/elasticsearch  # does not work for 5.x

xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false
